FROM --platform=linux/amd64 yourdevopsdena/python-slim:3.11

ENV MAIN_DIR /opt/services/kokbel/kokbel_backend
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN mkdir -p ${MAIN_DIR} && mkdir -p ${MAIN_DIR}/logs

WORKDIR ${MAIN_DIR}

COPY pyproject.toml uv.lock .

RUN uv pip install --system .

COPY .. ${MAIN_DIR}

RUN pip install -r requirements.txt \
    && pip install uv \
    && chmod -R 644 devops/entrypoints/backend_start.sh \   
    && chmod +x devops/entrypoints/backend_start.sh
