services:
  backend:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - back_static:/docker/back_static
      - back_media:/docker/back_media
      - apps:/docker/apps

volumes:
  back_static:
  back_media:
  apps: