# Generated by Django 5.2.8 on 2025-11-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='жанылыктын аталышын жазыныз', max_length=250, verbose_name='жанылыктын аталышы')),
                ('name_ru', models.CharField(help_text='жанылыктын аталышын жазыныз', max_length=250, null=True, verbose_name='жанылыктын аталышы')),
                ('name_ky', models.CharField(help_text='жанылыктын аталышын жазыныз', max_length=250, null=True, verbose_name='жанылыктын аталышы')),
                ('description', models.TextField(blank=True, help_text='жанылыктын толук маалыматы', verbose_name='толук маалымат')),
                ('description_ru', models.TextField(blank=True, help_text='жанылыктын толук маалыматы', null=True, verbose_name='толук маалымат')),
                ('description_ky', models.TextField(blank=True, help_text='жанылыктын толук маалыматы', null=True, verbose_name='толук маалымат')),
                ('date', models.CharField(help_text='Жанылыктын датасы', verbose_name='датасы')),
                ('date_ru', models.CharField(help_text='Жанылыктын датасы', null=True, verbose_name='датасы')),
                ('date_ky', models.CharField(help_text='Жанылыктын датасы', null=True, verbose_name='датасы')),
                ('image', models.ImageField(upload_to='news/images/', verbose_name='сүрөт')),
            ],
            options={
                'verbose_name': 'Жанылык',
                'verbose_name_plural': 'Жанылыклар',
            },
        ),
    ]
