# Generated by Django 5.2.6 on 2025-11-19 09:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='ФИО')),
                ('title_ru', models.CharField(max_length=155, null=True, verbose_name='ФИО')),
                ('title_ky', models.CharField(max_length=155, null=True, verbose_name='ФИО')),
                ('title_en', models.CharField(max_length=155, null=True, verbose_name='ФИО')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Сөзү (глава)')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Сөзү (глава)')),
                ('description_ky', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Сөзү (глава)')),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Сөзү (глава)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Главанын сүрөтү')),
            ],
            options={
                'verbose_name': 'Башкы бет',
                'verbose_name_plural': 'Башкы беттер',
            },
        ),
        migrations.CreateModel(
            name='HeadlinesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=255, verbose_name='Көк-Бел жергиликтүү өз алдынча башкаруусу')),
                ('title1_ru', models.CharField(max_length=255, null=True, verbose_name='Көк-Бел жергиликтүү өз алдынча башкаруусу')),
                ('title1_ky', models.CharField(max_length=255, null=True, verbose_name='Көк-Бел жергиликтүү өз алдынча башкаруусу')),
                ('title1_en', models.CharField(max_length=255, null=True, verbose_name='Көк-Бел жергиликтүү өз алдынча башкаруусу')),
                ('Announcements', models.CharField(max_length=255, verbose_name='Жарыялар')),
                ('Announcements_ru', models.CharField(max_length=255, null=True, verbose_name='Жарыялар')),
                ('Announcements_ky', models.CharField(max_length=255, null=True, verbose_name='Жарыялар')),
                ('Announcements_en', models.CharField(max_length=255, null=True, verbose_name='Жарыялар')),
                ('Latestannouncements', models.CharField(max_length=255, verbose_name='Акыркы жарыялар')),
                ('Latestannouncements_ru', models.CharField(max_length=255, null=True, verbose_name='Акыркы жарыялар')),
                ('Latestannouncements_ky', models.CharField(max_length=255, null=True, verbose_name='Акыркы жарыялар')),
                ('Latestannouncements_en', models.CharField(max_length=255, null=True, verbose_name='Акыркы жарыялар')),
                ('Anticorruptionmeasures', models.CharField(max_length=255, verbose_name='Антикоррупциялык чаралар')),
                ('Anticorruptionmeasures_ru', models.CharField(max_length=255, null=True, verbose_name='Антикоррупциялык чаралар')),
                ('Anticorruptionmeasures_ky', models.CharField(max_length=255, null=True, verbose_name='Антикоррупциялык чаралар')),
                ('Anticorruptionmeasures_en', models.CharField(max_length=255, null=True, verbose_name='Антикоррупциялык чаралар')),
                ('Governmentportal', models.CharField(max_length=255, verbose_name='Кыргыз Республикасынын мамлекеттик порталы')),
                ('Governmentportal_ru', models.CharField(max_length=255, null=True, verbose_name='Кыргыз Республикасынын мамлекеттик порталы')),
                ('Governmentportal_ky', models.CharField(max_length=255, null=True, verbose_name='Кыргыз Республикасынын мамлекеттик порталы')),
                ('Governmentportal_en', models.CharField(max_length=255, null=True, verbose_name='Кыргыз Республикасынын мамлекеттик порталы')),
                ('Jobs', models.CharField(max_length=255, verbose_name='Вакансиялар')),
                ('Jobs_ru', models.CharField(max_length=255, null=True, verbose_name='Вакансиялар')),
                ('Jobs_ky', models.CharField(max_length=255, null=True, verbose_name='Вакансиялар')),
                ('Jobs_en', models.CharField(max_length=255, null=True, verbose_name='Вакансиялар')),
                ('KokBelLocalGovernment', models.CharField(max_length=255, verbose_name='Көк-Бел жергиликтүү өз алдынча башкаруусу')),
                ('KokBelLocalGovernment_ru', models.CharField(max_length=255, null=True, verbose_name='Көк-Бел жергиликтүү өз алдынча башкаруусу')),
                ('KokBelLocalGovernment_ky', models.CharField(max_length=255, null=True, verbose_name='Көк-Бел жергиликтүү өз алдынча башкаруусу')),
                ('KokBelLocalGovernment_en', models.CharField(max_length=255, null=True, verbose_name='Көк-Бел жергиликтүү өз алдынча башкаруусу')),
            ],
            options={
                'verbose_name': 'Башкы беттеги заголовок',
                'verbose_name_plural': 'Башкы беттеги заголовоктор',
            },
        ),
    ]
