# Generated by Django 5.2.6 on 2025-11-19 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headlinesmodel',
            name='title1',
        ),
        migrations.RemoveField(
            model_name='headlinesmodel',
            name='title1_en',
        ),
        migrations.RemoveField(
            model_name='headlinesmodel',
            name='title1_ky',
        ),
        migrations.RemoveField(
            model_name='headlinesmodel',
            name='title1_ru',
        ),
    ]
