# Generated by Django 5.2.8 on 2025-11-25 10:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_headlinesmodel_title1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Логотип')),
                ('navigation', models.CharField(default='Навигация', max_length=200, verbose_name='Навигация')),
                ('home', models.CharField(default='Башкы', max_length=100, verbose_name='Башкы бет')),
                ('home_ru', models.CharField(default='Башкы', max_length=100, null=True, verbose_name='Башкы бет')),
                ('home_ky', models.CharField(default='Башкы', max_length=100, null=True, verbose_name='Башкы бет')),
                ('aiyl_aimagy', models.CharField(default='Айыл Аймагы', max_length=100, verbose_name='Айыл Аймагы')),
                ('aiyl_aimagy_ru', models.CharField(default='Айыл Аймагы', max_length=100, null=True, verbose_name='Айыл Аймагы')),
                ('aiyl_aimagy_ky', models.CharField(default='Айыл Аймагы', max_length=100, null=True, verbose_name='Айыл Аймагы')),
                ('aiyl_okmotu', models.CharField(default='Айыл Өкмөтү', max_length=100, verbose_name='Айыл Өкмөтү')),
                ('aiyl_okmotu_ru', models.CharField(default='Айыл Өкмөтү', max_length=100, null=True, verbose_name='Айыл Өкмөтү')),
                ('aiyl_okmotu_ky', models.CharField(default='Айыл Өкмөтү', max_length=100, null=True, verbose_name='Айыл Өкмөтү')),
                ('aiyldyk_kenesh', models.CharField(default='Айылдык Кеңеш', max_length=100, verbose_name='Айылдык Кеңеш')),
                ('aiyldyk_kenesh_ru', models.CharField(default='Айылдык Кеңеш', max_length=100, null=True, verbose_name='Айылдык Кеңеш')),
                ('aiyldyk_kenesh_ky', models.CharField(default='Айылдык Кеңеш', max_length=100, null=True, verbose_name='Айылдык Кеңеш')),
                ('obrashenie_gragdan', models.CharField(default='Жарандардын кайрылуулары', max_length=100, verbose_name='Жарандардын кайрылуулары')),
                ('obrashenie_gragdan_ru', models.CharField(default='Жарандардын кайрылуулары', max_length=100, null=True, verbose_name='Жарандардын кайрылуулары')),
                ('obrashenie_gragdan_ky', models.CharField(default='Жарандардын кайрылуулары', max_length=100, null=True, verbose_name='Жарандардын кайрылуулары')),
                ('novosti', models.CharField(default='Жаңылыктар', max_length=100, verbose_name='Жаңылыктар')),
                ('novosti_ru', models.CharField(default='Жаңылыктар', max_length=100, null=True, verbose_name='Жаңылыктар')),
                ('novosti_ky', models.CharField(default='Жаңылыктар', max_length=100, null=True, verbose_name='Жаңылыктар')),
                ('obiavlenie', models.CharField(default='Жарнамалар', max_length=100, verbose_name='Жарнамалар')),
                ('obiavlenie_ru', models.CharField(default='Жарнамалар', max_length=100, null=True, verbose_name='Жарнамалар')),
                ('obiavlenie_ky', models.CharField(default='Жарнамалар', max_length=100, null=True, verbose_name='Жарнамалар')),
                ('statistic_title', models.CharField(default='Статистика', help_text='Статистика бөлүмүнүн аталышы', max_length=100, verbose_name='Статистиканын аталышы')),
                ('show_statistics', models.BooleanField(default=True, verbose_name='Статистиканы көрсөтүү')),
                ('title_address', models.CharField(default='Адрес', help_text='Колонтитулда көрсөтүлө турган дарек сөзү', max_length=50, verbose_name='Адрес')),
                ('address', models.CharField(help_text='Колонтитулда көрсөтүлө турган дарек', max_length=50, verbose_name='Адрес')),
                ('address_ru', models.CharField(help_text='Колонтитулда көрсөтүлө турган дарек', max_length=50, null=True, verbose_name='Адрес')),
                ('address_ky', models.CharField(help_text='Колонтитулда көрсөтүлө турган дарек', max_length=50, null=True, verbose_name='Адрес')),
                ('title_phone', models.CharField(default='Телефон', help_text='Колонтитулда көрсөтүлө турган телефон сөзү', max_length=50, verbose_name='Телефон')),
                ('phone', models.CharField(help_text='Колонтитулда көрсөтүлө турган телефон номери', max_length=50, verbose_name='Телефон')),
                ('soicial_media', models.CharField(default='соц-тармак', max_length=50, verbose_name='соц-тармак')),
                ('soicial_media_ru', models.CharField(default='соц-тармак', max_length=50, null=True, verbose_name='соц-тармак')),
                ('soicial_media_ky', models.CharField(default='соц-тармак', max_length=50, null=True, verbose_name='соц-тармак')),
                ('facebook', models.URLField(blank=True, help_text='Facebook шилтемеңизди киргизиңиз', verbose_name='Социалдык тармак')),
            ],
            options={
                'verbose_name': 'Хэдер жана футер',
                'verbose_name_plural': 'Хэдерлер жана футерлер',
            },
        ),
        migrations.CreateModel(
            name='VisitorStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True, verbose_name='Дата')),
                ('visitors', models.IntegerField(default=0, verbose_name='Посетители')),
            ],
            options={
                'verbose_name': 'Статистика посещений',
                'verbose_name_plural': 'Статистика посещений',
            },
        ),
        migrations.AlterModelOptions(
            name='cartmodel',
            options={'verbose_name': 'Башчынын сөздөрү', 'verbose_name_plural': 'Башчынын сөздөрү'},
        ),
        migrations.RemoveField(
            model_name='cartmodel',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='cartmodel',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='headlinesmodel',
            name='Announcements_en',
        ),
        migrations.RemoveField(
            model_name='headlinesmodel',
            name='Anticorruptionmeasures_en',
        ),
        migrations.RemoveField(
            model_name='headlinesmodel',
            name='Governmentportal_en',
        ),
        migrations.RemoveField(
            model_name='headlinesmodel',
            name='Jobs_en',
        ),
        migrations.RemoveField(
            model_name='headlinesmodel',
            name='KokBelLocalGovernment_en',
        ),
        migrations.RemoveField(
            model_name='headlinesmodel',
            name='Latestannouncements_en',
        ),
    ]
