# Generated by Django 5.2.8 on 2025-11-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_footer_visitorstatistics_alter_cartmodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagetitlesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruraldistrict', models.CharField(default='Айылдык округ', max_length=255, verbose_name='Айылдык округ')),
                ('ruraldistrict_ru', models.CharField(default='Айылдык округ', max_length=255, null=True, verbose_name='Айылдык округ')),
                ('ruraldistrict_ky', models.CharField(default='Айылдык округ', max_length=255, null=True, verbose_name='Айылдык округ')),
                ('ruralcouncil', models.CharField(default='Айыл өкмөт', max_length=255, verbose_name='Айыл өкмөт')),
                ('ruralcouncil_ru', models.CharField(default='Айыл өкмөт', max_length=255, null=True, verbose_name='Айыл өкмөт')),
                ('ruralcouncil_ky', models.CharField(default='Айыл өкмөт', max_length=255, null=True, verbose_name='Айыл өкмөт')),
                ('villagecouncil', models.CharField(default='Айылдык кеңеш', max_length=255, verbose_name='Айылдык кеңеш')),
                ('villagecouncil_ru', models.CharField(default='Айылдык кеңеш', max_length=255, null=True, verbose_name='Айылдык кеңеш')),
                ('villagecouncil_ky', models.CharField(default='Айылдык кеңеш', max_length=255, null=True, verbose_name='Айылдык кеңеш')),
                ('news', models.CharField(default='Жанылыктар', max_length=255, verbose_name='Жанылыктар')),
                ('news_ru', models.CharField(default='Жанылыктар', max_length=255, null=True, verbose_name='Жанылыктар')),
                ('news_ky', models.CharField(default='Жанылыктар', max_length=255, null=True, verbose_name='Жанылыктар')),
                ('announcement', models.CharField(default='Жарнамалар', max_length=255, verbose_name='Жарнамалар')),
                ('announcement_ru', models.CharField(default='Жарнамалар', max_length=255, null=True, verbose_name='Жарнамалар')),
                ('announcement_ky', models.CharField(default='Жарнамалар', max_length=255, null=True, verbose_name='Жарнамалар')),
            ],
            options={
                'verbose_name': 'Беттеги аталыш',
                'verbose_name_plural': 'Беттеги аталыштар',
            },
        ),
    ]
