# Generated by Django 5.2.8 on 2025-11-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_pagetitlesmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Порталдын аталышы')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Порталдын аталышы')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Порталдын аталышы')),
                ('image', models.ImageField(upload_to='portal_images/', verbose_name='Порталдын сүрөтү')),
                ('link', models.URLField(verbose_name='Порталга шилтеме')),
            ],
            options={
                'verbose_name': 'Кыргыз Республикасынын мамлекеттик порталы',
                'verbose_name_plural': 'Кыргыз Республикасынын мамлекеттик порталдары',
            },
        ),
    ]
