# Generated by Django 5.2.8 on 2025-12-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_portal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartmodel',
            old_name='title',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='cartmodel',
            old_name='title_ky',
            new_name='full_name_ky',
        ),
        migrations.RenameField(
            model_name='cartmodel',
            old_name='title_ru',
            new_name='full_name_ru',
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='head',
            field=models.CharField(default='Көкбел айыл өкмөтүнүн башчысы', max_length=500, verbose_name='Көкбел айыл өкмөтүнүн башчысы'),
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='head_ky',
            field=models.CharField(default='Көкбел айыл өкмөтүнүн башчысы', max_length=500, null=True, verbose_name='Көкбел айыл өкмөтүнүн башчысы'),
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='head_ru',
            field=models.CharField(default='Көкбел айыл өкмөтүнүн башчысы', max_length=500, null=True, verbose_name='Көкбел айыл өкмөтүнүн башчысы'),
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='words',
            field=models.CharField(default='Башчынын сөзү', max_length=255, verbose_name='Башчынын сөзү'),
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='words_ky',
            field=models.CharField(default='Башчынын сөзү', max_length=255, null=True, verbose_name='Башчынын сөзү'),
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='words_ru',
            field=models.CharField(default='Башчынын сөзү', max_length=255, null=True, verbose_name='Башчынын сөзү'),
        ),
    ]
