# Generated by Django 5.2.8 on 2025-12-22 17:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_title_cartmodel_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Жаңылыктын аталышы')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Жаңылыктын аталышы')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Жаңылыктын аталышы')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Жаңылыктын сүрөттөлүшү')),
                ('description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Жаңылыктын сүрөттөлүшү')),
                ('description_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Жаңылыктын сүрөттөлүшү')),
                ('image', models.ImageField(upload_to='latest_news/', verbose_name='Жаңылыктын сүрөтү')),
            ],
            options={
                'verbose_name': 'Акыркы жаңылык',
                'verbose_name_plural': 'Акыркы жаңылыктар',
            },
        ),
    ]
