# Generated by Django 5.2.8 on 2025-12-23 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_visit_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='session_id',
        ),
    ]
