# Generated by Django 5.2.8 on 2025-12-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_visit_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetitlesmodel',
            name='appeals',
            field=models.CharField(default='Жарандардын кайрылуулары', max_length=255, verbose_name='Жарандардын кайрылуулары'),
        ),
        migrations.AddField(
            model_name='pagetitlesmodel',
            name='appeals_ky',
            field=models.CharField(default='Жарандардын кайрылуулары', max_length=255, null=True, verbose_name='Жарандардын кайрылуулары'),
        ),
        migrations.AddField(
            model_name='pagetitlesmodel',
            name='appeals_ru',
            field=models.CharField(default='Жарандардын кайрылуулары', max_length=255, null=True, verbose_name='Жарандардын кайрылуулары'),
        ),
        migrations.AddField(
            model_name='pagetitlesmodel',
            name='base',
            field=models.CharField(default='Башкы бет', max_length=255, verbose_name='Башкы бет'),
        ),
        migrations.AddField(
            model_name='pagetitlesmodel',
            name='base_ky',
            field=models.CharField(default='Башкы бет', max_length=255, null=True, verbose_name='Башкы бет'),
        ),
        migrations.AddField(
            model_name='pagetitlesmodel',
            name='base_ru',
            field=models.CharField(default='Башкы бет', max_length=255, null=True, verbose_name='Башкы бет'),
        ),
    ]
