# Generated by Django 5.2.8 on 2025-12-26 05:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_pagetitlesmodel_appeals_pagetitlesmodel_appeals_ky_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Баракчага кирүү',
                'verbose_name_plural': 'Баракчага кирүүлөр',
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('visit_count', models.PositiveIntegerField(default=0)),
                ('last_visit', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Визит',
                'verbose_name_plural': 'Визиттер',
            },
        ),
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
