# Generated by Django 5.2.8 on 2026-01-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_pagevisit_visitor_delete_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Сөзү (глава)'),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='description_ky',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Сөзү (глава)'),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='description_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Сөзү (глава)'),
        ),
    ]
