# Generated by Django 5.2.8 on 2025-11-26 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeAdministration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, verbose_name='Айыл өкмөтүнүн түрүнүн аталышы')),
            ],
            options={
                'verbose_name': 'Айыл өкмөтүнүн түрү',
                'verbose_name_plural': 'Айыл өкмөтүнүн түрлөрү',
            },
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='Кызматы', max_length=255, verbose_name='Кызматы')),
                ('full_name', models.CharField(max_length=500, verbose_name='Толук аты-жөнү')),
                ('reseptions', models.CharField(max_length=500, verbose_name='Кабыл алуу күнү жана убактысы')),
                ('image', models.ImageField(upload_to='management/', verbose_name='Сүрөтү')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='management', to='administration.typeadministration', verbose_name='Айыл өкмөтүнүн түрү')),
            ],
            options={
                'verbose_name': 'Айыл өкмөтүнүн жетекчилиги',
                'verbose_name_plural': 'Айыл өкмөтүнүн жетекчилиги',
            },
        ),
    ]
