# Generated by Django 5.2.8 on 2025-11-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='management',
            name='full_name_ky',
            field=models.CharField(max_length=500, null=True, verbose_name='Толук аты-жөнү'),
        ),
        migrations.AddField(
            model_name='management',
            name='full_name_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Толук аты-жөнү'),
        ),
        migrations.AddField(
            model_name='management',
            name='reseptions_ky',
            field=models.CharField(max_length=500, null=True, verbose_name='Кабыл алуу күнү жана убактысы'),
        ),
        migrations.AddField(
            model_name='management',
            name='reseptions_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Кабыл алуу күнү жана убактысы'),
        ),
        migrations.AddField(
            model_name='management',
            name='role_ky',
            field=models.CharField(default='Кызматы', max_length=255, null=True, verbose_name='Кызматы'),
        ),
        migrations.AddField(
            model_name='management',
            name='role_ru',
            field=models.CharField(default='Кызматы', max_length=255, null=True, verbose_name='Кызматы'),
        ),
        migrations.AddField(
            model_name='typeadministration',
            name='type_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Айыл өкмөтүнүн түрүнүн аталышы'),
        ),
        migrations.AddField(
            model_name='typeadministration',
            name='type_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Айыл өкмөтүнүн түрүнүн аталышы'),
        ),
    ]
