# Generated by Django 5.2.8 on 2025-11-27 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_management_full_name_ky_management_full_name_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='structure', verbose_name='Сүрөт')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.typeadministration', verbose_name='Курулуш')),
            ],
            options={
                'verbose_name': 'Курулуш',
                'verbose_name_plural': 'Курулушу',
            },
        ),
    ]
