# Generated by Django 5.2.8 on 2025-11-27 11:26

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.typeadministration', verbose_name='Түрү'),
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Аталышы')),
                ('title_ru', models.CharField(max_length=500, null=True, verbose_name='Аталышы')),
                ('title_ky', models.CharField(max_length=500, null=True, verbose_name='Аталышы')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Түшүндүрмөсү')),
                ('description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Түшүндүрмөсү')),
                ('description_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Түшүндүрмөсү')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.typeadministration', verbose_name='Түрү')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансиялар',
            },
        ),
    ]
