# Generated by Django 5.2.8 on 2025-11-27 12:29

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_alter_structure_type_vacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntiCorruptionMeasures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Аталышы', max_length=500, verbose_name='Аталышы')),
                ('title_ru', models.CharField(default='Аталышы', max_length=500, null=True, verbose_name='Аталышы')),
                ('title_ky', models.CharField(default='Аталышы', max_length=500, null=True, verbose_name='Аталышы')),
                ('real_title', models.CharField(max_length=500, verbose_name='Аталышы')),
                ('real_title_ru', models.CharField(max_length=500, null=True, verbose_name='Аталышы')),
                ('real_title_ky', models.CharField(max_length=500, null=True, verbose_name='Аталышы')),
                ('description', ckeditor.fields.RichTextField(default='Түшүндүрмөсү', verbose_name='Түшүндүрмөсү')),
                ('description_ru', ckeditor.fields.RichTextField(default='Түшүндүрмөсү', null=True, verbose_name='Түшүндүрмөсү')),
                ('description_ky', ckeditor.fields.RichTextField(default='Түшүндүрмөсү', null=True, verbose_name='Түшүндүрмөсү')),
                ('real_description', ckeditor.fields.RichTextField(verbose_name='Түшүндүрмөсү')),
                ('real_description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Түшүндүрмөсү')),
                ('real_description_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Түшүндүрмөсү')),
                ('file', models.FileField(upload_to='anti_corrup_docs/', verbose_name='Файл (DOCX/PDF)')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.typeadministration', verbose_name='Түрү')),
            ],
            options={
                'verbose_name': 'Коррупцияга каршы чара',
                'verbose_name_plural': 'Коррупцияга каршы чаралар',
            },
        ),
    ]
