# Generated by Django 5.2.8 on 2025-11-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_anticorruptionmeasures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anticorruptionmeasures',
            name='description',
            field=models.CharField(default='Түшүндүрмөсү', max_length=500, verbose_name='Түшүндүрмөсү'),
        ),
        migrations.AlterField(
            model_name='anticorruptionmeasures',
            name='description_ky',
            field=models.CharField(default='Түшүндүрмөсү', max_length=500, null=True, verbose_name='Түшүндүрмөсү'),
        ),
        migrations.AlterField(
            model_name='anticorruptionmeasures',
            name='description_ru',
            field=models.CharField(default='Түшүндүрмөсү', max_length=500, null=True, verbose_name='Түшүндүрмөсү'),
        ),
    ]
