# Generated by Django 5.2.8 on 2025-11-27 16:09

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_alter_anticorruptionmeasures_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Аталышы')),
                ('title_ru', models.CharField(max_length=500, null=True, verbose_name='Аталышы')),
                ('title_ky', models.CharField(max_length=500, null=True, verbose_name='Аталышы')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Түшүндүрмөсү')),
                ('description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Түшүндүрмөсү')),
                ('description_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Түшүндүрмөсү')),
            ],
            options={
                'verbose_name': 'Эсеп',
                'verbose_name_plural': 'Эсептер',
            },
        ),
        migrations.CreateModel(
            name='ReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='report', verbose_name='Сүрөт')),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='administration.report', verbose_name='Эсеп')),
            ],
            options={
                'verbose_name': 'Сүрөт',
                'verbose_name_plural': 'Сүрөттөр',
            },
        ),
    ]
