# Generated by Django 5.2.8 on 2025-11-27 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_report_reportimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.typeadministration', verbose_name='Түрү'),
        ),
    ]
