# Generated by Django 5.2.8 on 2025-11-27 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_report_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleAdministration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Аталышы')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Аталышы')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Аталышы')),
            ],
            options={
                'verbose_name': 'Айыл өкмөтүнүн темасы',
                'verbose_name_plural': 'Айыл өкмөтүнүн темалары',
            },
        ),
        migrations.AddField(
            model_name='anticorruptionmeasures',
            name='common_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.titleadministration', verbose_name='Темасы'),
        ),
        migrations.AddField(
            model_name='report',
            name='common_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.titleadministration', verbose_name='Темасы'),
        ),
    ]
