# Generated by Django 5.2.8 on 2025-11-29 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_titleadministration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anticorruptionmeasures',
            name='content_html',
            field=models.TextField(blank=True, verbose_name='Документтин HTML түрү'),
        ),
    ]
