# Generated by Django 5.2.8 on 2025-12-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_anticorruptionmeasures_content_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='anticorruptionmeasures',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='anti_corrup_images/', verbose_name='Сүрөт'),
        ),
    ]
