# Generated by Django 5.2.8 on 2025-12-24 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_anticorruptionmeasures_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anticorruptionmeasures',
            name='content_html',
        ),
    ]
