# Generated by Django 5.2.6 on 2025-11-21 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CouncilSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Бөлүм аталышы')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Бөлүм аталышы')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Бөлүм аталышы')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Бөлүм аталышы')),
                ('detail_title', models.CharField(blank=True, max_length=255, verbose_name='Толук аталышы')),
                ('detail_title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Толук аталышы')),
                ('detail_title_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='Толук аталышы')),
                ('detail_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Толук аталышы')),
            ],
            options={
                'verbose_name': 'Айылдык кеңеш бөлүмү',
                'verbose_name_plural': 'Айылдык кеңеш бөлүмдөрү',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CouncilDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Документтин аталышы')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Документтин аталышы')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Документтин аталышы')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Документтин аталышы')),
                ('description', models.TextField(blank=True, verbose_name='Документтин сүрөттөлүшү')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Документтин сүрөттөлүшү')),
                ('description_ky', models.TextField(blank=True, null=True, verbose_name='Документтин сүрөттөлүшү')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Документтин сүрөттөлүшү')),
                ('file', models.FileField(upload_to='council_docs/', verbose_name='Файл (DOCX/PDF)')),
                ('content_html', models.TextField(blank=True, verbose_name='Документтин HTML түрү')),
                ('content_html_ru', models.TextField(blank=True, null=True, verbose_name='Документтин HTML түрү')),
                ('content_html_ky', models.TextField(blank=True, null=True, verbose_name='Документтин HTML түрү')),
                ('content_html_en', models.TextField(blank=True, null=True, verbose_name='Документтин HTML түрү')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='kenesh.councilsection', verbose_name='Бөлүм')),
            ],
            options={
                'verbose_name': 'Айылдык кеңеш документи',
                'verbose_name_plural': 'Айылдык кеңеш документтери',
                'ordering': ['id'],
            },
        ),
    ]
