# Generated by Django 5.2.6 on 2025-11-25 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kenesh', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='councildocument',
            name='content_html_en',
        ),
        migrations.RemoveField(
            model_name='councildocument',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='councildocument',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='councilsection',
            name='detail_title_en',
        ),
        migrations.RemoveField(
            model_name='councilsection',
            name='title_en',
        ),
    ]
