# Generated by Django 5.2.8 on 2025-11-28 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kenesh', '0002_remove_councildocument_content_html_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='councildocument',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='kenesh.councilsection', verbose_name='Бөлүм'),
        ),
        migrations.CreateModel(
            name='Deputies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255, verbose_name='Депутаттын кызматы')),
                ('position_ru', models.CharField(max_length=255, null=True, verbose_name='Депутаттын кызматы')),
                ('position_ky', models.CharField(max_length=255, null=True, verbose_name='Депутаттын кызматы')),
                ('name', models.CharField(max_length=255, verbose_name='Депутаттын аты-жөнү')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Депутаттын аты-жөнү')),
                ('name_ky', models.CharField(max_length=255, null=True, verbose_name='Депутаттын аты-жөнү')),
                ('contact', models.CharField(default='Байланыш маалыматтары', max_length=255, verbose_name='Байланыш маалыматтары')),
                ('contact_ru', models.CharField(default='Байланыш маалыматтары', max_length=255, null=True, verbose_name='Байланыш маалыматтары')),
                ('contact_ky', models.CharField(default='Байланыш маалыматтары', max_length=255, null=True, verbose_name='Байланыш маалыматтары')),
                ('real_contact', models.CharField(blank=True, max_length=255, verbose_name='Чыныгы байланыш маалыматтары')),
                ('district', models.CharField(default='Шайлоо округуна тиешелүүлүгү', max_length=255, verbose_name='Депутаттын шайланган аймагы')),
                ('district_ru', models.CharField(default='Шайлоо округуна тиешелүүлүгү', max_length=255, null=True, verbose_name='Депутаттын шайланган аймагы')),
                ('district_ky', models.CharField(default='Шайлоо округуна тиешелүүлүгү', max_length=255, null=True, verbose_name='Депутаттын шайланган аймагы')),
                ('real_district', models.CharField(max_length=255, verbose_name='Чыныгы депутаттын шайланган аймагы')),
                ('real_district_ru', models.CharField(max_length=255, null=True, verbose_name='Чыныгы депутаттын шайланган аймагы')),
                ('real_district_ky', models.CharField(max_length=255, null=True, verbose_name='Чыныгы депутаттын шайланган аймагы')),
                ('faction', models.CharField(default='Фракцияга тиешелүүлүгү', max_length=255, verbose_name='Фракция')),
                ('faction_ru', models.CharField(default='Фракцияга тиешелүүлүгү', max_length=255, null=True, verbose_name='Фракция')),
                ('faction_ky', models.CharField(default='Фракцияга тиешелүүлүгү', max_length=255, null=True, verbose_name='Фракция')),
                ('real_faction', models.CharField(max_length=255, verbose_name='Чыныгы фракция')),
                ('real_faction_ru', models.CharField(max_length=255, null=True, verbose_name='Чыныгы фракция')),
                ('real_faction_ky', models.CharField(max_length=255, null=True, verbose_name='Чыныгы фракция')),
                ('role', models.CharField(default='Кайсы комиссияга тиешелүү жана кайсы кызматты ээлейт', max_length=255, verbose_name='Депутаттын ролу')),
                ('role_ru', models.CharField(default='Кайсы комиссияга тиешелүү жана кайсы кызматты ээлейт', max_length=255, null=True, verbose_name='Депутаттын ролу')),
                ('role_ky', models.CharField(default='Кайсы комиссияга тиешелүү жана кайсы кызматты ээлейт', max_length=255, null=True, verbose_name='Депутаттын ролу')),
                ('real_role', models.CharField(max_length=255, verbose_name='Чыныгы депутаттын ролу')),
                ('real_role_ru', models.CharField(max_length=255, null=True, verbose_name='Чыныгы депутаттын ролу')),
                ('real_role_ky', models.CharField(max_length=255, null=True, verbose_name='Чыныгы депутаттын ролу')),
                ('image', models.ImageField(upload_to='deputies/', verbose_name='Депутаттын сүрөтү')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deputies', to='kenesh.councilsection', verbose_name='Бөлүм')),
            ],
            options={
                'verbose_name': 'Айылдык кеңеш депутаты',
                'verbose_name_plural': 'Айылдык кеңеш депутаттары',
                'ordering': ['id'],
            },
        ),
    ]
