# Generated by Django 5.2.8 on 2025-11-29 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kenesh', '0004_commission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='councilsection',
            options={'ordering': ['id'], 'verbose_name': 'Айылдык кеңеш бөлүм түрү', 'verbose_name_plural': 'Айылдык кеңеш бөлүмүнүн түрлөрү'},
        ),
    ]
