# Generated by Django 5.2.8 on 2025-12-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kenesh', '0005_alter_councilsection_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deputies',
            options={'ordering': ['-is_first', 'name'], 'verbose_name': 'Айылдык кеңеш депутаты', 'verbose_name_plural': 'Айылдык кеңеш депутаттары'},
        ),
        migrations.AddField(
            model_name='deputies',
            name='is_first',
            field=models.BooleanField(default=False, verbose_name='Биринчи'),
        ),
    ]
