# Generated by Django 5.2.8 on 2025-12-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kenesh', '0006_alter_deputies_options_deputies_is_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='councildocument',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='council_docs/pdf/', verbose_name='PDF файл'),
        ),
    ]
