# Generated by Django 5.2.8 on 2025-12-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kenesh', '0007_councildocument_pdf_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='councildocument',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Айылдык кеңеш документи', 'verbose_name_plural': 'Айылдык кеңеш документтери'},
        ),
        migrations.AddField(
            model_name='councildocument',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок документа'),
        ),
    ]
