# Generated by Django 5.2.8 on 2025-12-24 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kenesh', '0008_alter_councildocument_options_councildocument_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='councildocument',
            options={'ordering': ['id'], 'verbose_name': 'Айылдык кеңеш документи', 'verbose_name_plural': 'Айылдык кеңеш документтери'},
        ),
        migrations.RemoveField(
            model_name='councildocument',
            name='order',
        ),
    ]
