# Generated by Django 5.2.8 on 2025-12-24 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kenesh', '0009_alter_councildocument_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='councildocument',
            name='content_html',
        ),
        migrations.RemoveField(
            model_name='councildocument',
            name='content_html_ky',
        ),
        migrations.RemoveField(
            model_name='councildocument',
            name='content_html_ru',
        ),
        migrations.RemoveField(
            model_name='councildocument',
            name='pdf_file',
        ),
    ]
