# Generated by Django 5.2.8 on 2025-11-27 17:22

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=255, verbose_name='Жылы')),
                ('date_ru', models.CharField(max_length=255, null=True, verbose_name='Жылы')),
                ('date_ky', models.CharField(max_length=255, null=True, verbose_name='Жылы')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Түшүндүрмөсү')),
                ('description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Түшүндүрмөсү')),
                ('description_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Түшүндүрмөсү')),
            ],
            options={
                'verbose_name': 'Айыл аймагы жөнүндө',
                'verbose_name_plural': 'Айыл аймагы жөнүндө',
            },
        ),
        migrations.CreateModel(
            name='TypeTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=500, verbose_name='Түрү')),
                ('type_ru', models.CharField(max_length=500, null=True, verbose_name='Түрү')),
                ('type_ky', models.CharField(max_length=500, null=True, verbose_name='Түрү')),
                ('title', models.CharField(max_length=500, verbose_name='Аталышы')),
                ('title_ru', models.CharField(max_length=500, null=True, verbose_name='Аталышы')),
                ('title_ky', models.CharField(max_length=500, null=True, verbose_name='Аталышы')),
            ],
            options={
                'verbose_name': 'Айыл аймак',
                'verbose_name_plural': 'Айыл аймагы',
            },
        ),
        migrations.CreateModel(
            name='DataImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='report', verbose_name='Сүрөт')),
                ('data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='district.data', verbose_name='Маалыматтар')),
            ],
            options={
                'verbose_name': 'Сүрөт',
                'verbose_name_plural': 'Сүрөттөр',
            },
        ),
        migrations.AddField(
            model_name='data',
            name='type_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data', to='district.typetitle', verbose_name='Түрү'),
        ),
    ]
