# Generated by Django 5.2.8 on 2025-11-28 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typetitle',
            options={'verbose_name': 'Айыл аймагынын түрү', 'verbose_name_plural': 'Айыл аймагынын түрлөрү'},
        ),
    ]
