# Generated by Django 5.2.8 on 2025-12-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0002_alter_typetitle_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='date_ky',
        ),
        migrations.RemoveField(
            model_name='data',
            name='date_ru',
        ),
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.DateField(verbose_name='Жылы'),
        ),
    ]
