# Generated by Django 5.2.6 on 2025-11-18 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name': 'Название', 'verbose_name_plural': 'Названия'},
        ),
        migrations.AddField(
            model_name='announcement',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='link_en',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='link_ky',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='link_ru',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='title_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='объявления', to='notifications.title'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='title_ky',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='объявления', to='notifications.title'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='title_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='объявления', to='notifications.title'),
        ),
        migrations.AddField(
            model_name='title',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='name_ky',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(upload_to='объявления/'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='объявления', to='notifications.title'),
        ),
    ]
