# Generated by Django 5.2.8 on 2025-11-26 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='types_ky',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='types_ru',
        ),
    ]
