# Generated by Django 5.2.8 on 2025-12-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_notification_types_ky_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активдүү'),
        ),
    ]
