# Generated by Django 5.2.6 on 2025-11-22 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_announcement_options_alter_title_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(upload_to='announcements/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='notifications.title', verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='notifications.title', verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title_ky',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='notifications.title', verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='notifications.title', verbose_name='Название'),
        ),
    ]
