# Generated by Django 5.2.6 on 2025-11-22 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_announcement_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['id'], 'verbose_name': 'Айылдык кеңеш жарыя', 'verbose_name_plural': 'Айылдык кеңеш жарыялар'},
        ),
        migrations.RemoveField(
            model_name='title',
            name='name',
        ),
        migrations.RemoveField(
            model_name='title',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='title',
            name='name_ky',
        ),
        migrations.RemoveField(
            model_name='title',
            name='name_ru',
        ),
        migrations.AddField(
            model_name='title',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='Бөлүм аталышы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='title',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Бөлүм аталышы'),
        ),
        migrations.AddField(
            model_name='title',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Бөлүм аталышы'),
        ),
        migrations.AddField(
            model_name='title',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Бөлүм аталышы'),
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Айылдык кеңеш жарыясынын аталышы')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Айылдык кеңеш жарыясынын аталышы')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Айылдык кеңеш жарыясынын аталышы')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Айылдык кеңеш жарыясынын аталышы')),
                ('description', models.TextField(blank=True, verbose_name='Айылдык кеңеш жарыясынын сүрөттөлүшү')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Айылдык кеңеш жарыясынын сүрөттөлүшү')),
                ('description_ky', models.TextField(blank=True, null=True, verbose_name='Айылдык кеңеш жарыясынын сүрөттөлүшү')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Айылдык кеңеш жарыясынын сүрөттөлүшү')),
                ('file', models.FileField(upload_to='notifications/', verbose_name='Айылдык кеңеш жарыясынын файлы (DOCX/PDF)')),
                ('content_html', models.TextField(blank=True, verbose_name='Айылдык кеңеш жарыясынын HTML түрү')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='notifications.title', verbose_name='Айылдык кеңеш жарыя')),
            ],
            options={
                'verbose_name': 'Айылдык кеңеш жарыясынын маалыматы',
                'verbose_name_plural': 'Айылдык кеңеш жарыясынын маалыматтары',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
