# Generated by Django 5.2.6 on 2025-11-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_title_options_remove_title_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='content_html',
        ),
        migrations.RemoveField(
            model_name='description',
            name='file',
        ),
        migrations.AddField(
            model_name='description',
            name='image',
            field=models.ImageField(default=1, upload_to='notifications/', verbose_name='Айылдык кеңеш жарыясынын cүрөтү'),
            preserve_default=False,
        ),
    ]
