# Generated by Django 5.2.6 on 2025-11-25 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_title_options_remove_title_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='description',
            options={'ordering': ['id'], 'verbose_name': 'Оповещение', 'verbose_name_plural': 'Оповещения'},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['id'], 'verbose_name': 'Блок оповещений', 'verbose_name_plural': 'Блоки оповещений'},
        ),
        migrations.RemoveField(
            model_name='description',
            name='content_html',
        ),
        migrations.RemoveField(
            model_name='description',
            name='file',
        ),
        migrations.AddField(
            model_name='description',
            name='image',
            field=models.ImageField(blank=True, upload_to='notifications/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='description',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='description',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='description',
            name='description_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='description',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='description',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='notifications.title', verbose_name='Блок оповещений'),
        ),
        migrations.AlterField(
            model_name='description',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='description',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='description',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='description',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='title',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок блока'),
        ),
        migrations.AlterField(
            model_name='title',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок блока'),
        ),
        migrations.AlterField(
            model_name='title',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок блока'),
        ),
        migrations.AlterField(
            model_name='title',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок блока'),
        ),
    ]
