# Generated by Django 5.2.6 on 2025-11-25 02:32

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_remove_description_content_html_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, verbose_name='Түрүнүн аталышы')),
                ('type_ru', models.CharField(max_length=255, null=True, verbose_name='Түрүнүн аталышы')),
                ('type_ky', models.CharField(max_length=255, null=True, verbose_name='Түрүнүн аталышы')),
                ('type_en', models.CharField(max_length=255, null=True, verbose_name='Түрүнүн аталышы')),
            ],
            options={
                'verbose_name': 'Жарнаманын түрү',
                'verbose_name_plural': 'Жарнамалардын түрү',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Аталышы')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Аталышы')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Аталышы')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Аталышы')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Сүрөттөмө')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Сүрөттөмө')),
                ('description_ky', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Сүрөттөмө')),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Сүрөттөмө')),
                ('image', models.ImageField(upload_to='notifications/', verbose_name='Жарнаманын cүрөтү')),
                ('types', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification', to='notifications.typenotification', verbose_name='Жарнаманын түрү')),
                ('types_en', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification', to='notifications.typenotification', verbose_name='Жарнаманын түрү')),
                ('types_ky', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification', to='notifications.typenotification', verbose_name='Жарнаманын түрү')),
                ('types_ru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification', to='notifications.typenotification', verbose_name='Жарнаманын түрү')),
            ],
            options={
                'verbose_name': 'Жарнама',
                'verbose_name_plural': 'Жарнамалар',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Description',
        ),
        migrations.DeleteModel(
            name='Title',
        ),
    ]
