# Generated by Django 5.2.6 on 2025-11-25 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_typenotification_notification_delete_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='types_en',
        ),
        migrations.RemoveField(
            model_name='typenotification',
            name='type_en',
        ),
        migrations.AddField(
            model_name='notification',
            name='date',
            field=models.CharField(default=1, max_length=255, verbose_name='Күнү'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='date_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Күнү'),
        ),
        migrations.AddField(
            model_name='notification',
            name='date_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Күнү'),
        ),
    ]
